### ISSUE TITLE
実践リーダブルコード 2015-03-06

### ISSUE THREAD

**Issue by kou** [clear-code/readable-code-workshop#1]
2015年3月6日（金）開催の[実践リーダブルコード](http://event.shoeisha.jp/aa/20150306/)で情報共有に使うためのissueです。

次の用途に使います。
- 参加者のリポジトリーのURLの共有
- 参加者からの質問受け付け窓口

**Comment by myokoym** [comment]
チーム○の横山（C言語）のリポジトリーのURLです。
https://github.com/myokoym/myokoym-readable-code-workshop

**Comment by myokoym** [comment]
チーム○の横山（Ruby）のリポジトリーのURLです。
https://github.com/myokoym/myokoym-readable-code-workshop-ruby

**Comment by toshi0383** [comment]
チームBの鈴木俊（Java）のリポジトリのURLです。
https://github.com/toshi0383/toshi0383-readable-code

**Comment by Takajin** [comment]
チームAのやしき（Java）のリポジトリのURLです。
https://github.com/Takajin/yashiki-readable-code

**Comment by terahide** [comment]
チームBのてらひでのリポジトリのURLです。
https://github.com/terahide/terahide-readable-code

**Comment by BocchiP3** [comment]
チームCのもりや（JavaScript）のリポジトリのURLです。
https://github.com/glassman21/glassman21-readable-code

**Comment by isozumi** [comment]
チームBの五十住（java）のリポジトリURLです
https://github.com/isozumi/isozumi-readable-code

**Comment by yukokondo** [comment]
チームCの近藤（Ruby）のリポジトリのURLです。
https://github.com/yukokondo/yukokondo-readable-code

**Comment by Fermithrax77** [comment]
チームAの梶家（Java）のリポジトリのURLです。
https://github.com/Fermithrax77/Fermithrax77-readable-code/tree/master/SamplePJ

**Comment by szkayeah** [comment]
チームA？の鈴木亜(Java)のリポジトリURLです。
https://github.com/szkayeah/szkayeah-readable-code

**Comment by masanori-matsuda** [comment]
チームCの松田(JavaScript)のリポジトリのURLです。
https://github.com/masanori-matsuda/masanori-matsuda-readable-code

**Comment by ghost** [comment]
チームAの渡邉(Java)のリポジトリURLです。
https://github.com/WatanabeKouji/WanatanabeKouji-readable-code

**Comment by yamashiro000** [comment]
チームCの山城（Ｃ＋＋）のリポジトリURLです。
https://github.com/yamashiro000/yamashiro000-readable-code

**Comment by sn1w** [comment]
チームBの岩井(Java)のリポジトリURLです。
https://github.com/shiwai/shiwai-readable-code

**Comment by myokoym** [comment]
チーム〇の横山（Java）のリポジトリーのURLです。
 https://github.com/myokoym/myokoym-readable-code-workshop-java

**Comment by terahide** [comment]
どやｗ！ 
https://github.com/terahide/terahide-readable-code

**Comment by kou** [comment]
講座が終わったので閉じます。

閉じますが、なにか追加で聞きたいことがあれば書き込んでもらえれば回答します。

もし、会社に戻ってから行動してみてうまくいったこと障壁だったことなど、公開できる（他の参加者に共有できる）ものであれば書き込んでもらうとうれしい人がいるかもしれません。

参加者のみなさんにはいろいろ助けてもらったなぁと感じています。（積極的に発言したり、相談してくれたりとか。）
参加、ありがとうございました！応援しています！
