### ISSUE TITLE
2015-08-11: リーダブルコードメモ

### ISSUE THREAD

**Issue by kou** [clear-code/readable-code-workshop#10]
「自分が書いたリーダブルコード」と「自分が見つけたリーダブルコード」をここにメモしていっていてください。目的は「リーダブルコードを見つける練習」です。単に「書く」「見つける」だけでなく、「メモとしてまとめる」ことまですることで「再利用可能な状態」（＝他の人に説明できる、他の場面で同じ書き方を適用できる）まで自分の中で整理されることを期待しています。

1つのリーダブルコードにつき1つのコメントにしてください。

各コメントには次の内容を含めてください。
- サマリー（あるいはタイトルあるいは一言説明）
- 実際のコード
- どうしてリーダブルだと考えたかの説明
- 「見つけた」場合のみ：見つけた経緯（あるいはきっかけ）

コメントに書くときは次のテンプレートを使ってください。

``````
### サマリー

（ここにサマリーを書く）

### 実際のコード

```ruby
（ここに実際のコードを書く）
```

### どうしてリーダブルだと考えたかの説明

（ここに説明を書く）

### 見つけた経緯

（「見つけた」場合のみ。ここに見つけた経緯を書く。）
``````

以下は具体例です。

---
### サマリー

自己記述的定数名
### 実際のコード

https://github.com/doraemon13x/doraemon13x-sezemi-2014-readable-code-2/blob/master/mission3.c#L9

``` c
exit(EXIT_FAILURE); /* エラーの場合は異常終了する */
```
### どうしてリーダブルだと考えたかの説明

コマンドの終了ステータスは、正常終了するときは`0`、異常終了するときは`0`以外の値を返すのが通例です。そのため、このコードは次のようにしても通例通りの動きになります。

``` c
exit(1);
```

ただ、動くのは動きますが、`EXIT_FAILURE`という名前を使っている方が「失敗して終了するんだな」というのがわかりやすいのでリーダブルだと考えました。

なお、`EXIT_SUCCESS`というのもあるので、同様の理由で正常終了するときはそれを使うのがよいと思います。
### 見つけた経緯

ちゃんとエラー処理をしていて立派だなぁと思って読み進めたら異常終了することがわかりやすいコードだと気づきました。

---

**Comment by ik11235** [comment]
### サマリー

実行環境構築Howto

### 実際のコード

``````
## 前提準備
rubyが必須
Macではデフォルトで入っているが、windows,Linuxではインストールが必要。
### Windows
[ダウンロード](https://www.ruby-lang.org/ja/downloads/)より、Windows用のRubyをダウンロード、インストール
### Linux
```sh
sudo apt-get install ruby
```
or

```sh
sudo yum install ruby
```
``````

### どうしてリーダブルだと考えたかの説明

自分の開発環境で動かしている場合、すでにライブラリなどはインストール済みのためそのまま動くが、
他者が検証する場合に何かしらのライブラリなどのインストールが必要な場合、コードからそれを読み解くのは時間がかかるため、READMEに記載する、Gemfileに記載した上で`bundle install`の実行を指示するなど、すぐに実行環境を整え、開発に移れることもリーダブルなコードであると考えたため。

**Comment by alpaca-tc** [comment]
### 名前

ARGVの処理をOptionParserで行う

### 実際のコード

``` ruby
require 'optparse'

module Recipe
  class Option
    def initialize(argv)
      @argv = argv.clone
    end

    def parse!
      opts = OptionParser.new

      opts.on('--path [Recipe YAML DATA]') do |path|
        configuration[:recipe_path] = path
      end

      opts.parse!(@argv)
    end

    private

    def configuration
      Recipe.configuration
    end
  end
end
```

### どうしてリーダブルだと考えたかの説明

標準ライブラリであるOptionParserを使用することで、誰でも理解可能なコードを書くことができる。
`--help`を渡すことでオプションの説明をしてくれるので、今後オプションが増えた際にもREADMEを編集する手間を減らすことができる。

**Comment by ik11235** [comment]
### サマリー

README上の書式の統一

### 実際のコード

``````
## インストール手順
### Linux
```sh
sudo apt-get install ruby
```
## 実行例
ruby ./recipe.rb
``````

↓

``````
## インストール手順
### Linux
```sh
sudo apt-get install ruby
```
## 実行例
```sh
ruby ./recipe.rb
```
``````

### どうしてリーダブルだと考えたかの説明

READMEから、順に開発環境構築->実行テストなどと進めていく中で、同じターミナル上で行う動作であればshのコードブロックで表記するなど、表記が統一されていれば、すぐにどこで何をするべきかを理解できると考えたため。

**Comment by ik11235** [comment]
### サマリー

固有値の変数・定数化

### 実際のコード

``` ruby
recipe_data_file_path = './recipe-data.txt'

recipe_file = open(recipe_data_file_path)
```

### どうしてリーダブルだと考えたかの説明

特定の文字列や数値がどういった意味を持つ値なのかを、変数・定数名で明確にすることで、その使用箇所でどういった意味の値が使わえているかをすぐにわかると考えたため。

**Comment by tkm-kj** [comment]
### サマリー

オムライスを出力できるようにした

### 実際のコード

``` ruby
class Recipe
  def initialize(name)
    puts name
  end
end

Recipe.new('オムライス')
```

### どうしてリーダブルだと考えたかの説明

今後様々な仕様が来ても対応出来るようにするために、Recipeクラスを作ってそこに処理を書いた。

### 見つけた経緯

（「見つけた」場合のみ。ここに見つけた経緯を書く。）

**Comment by tkm-kj** [comment]
### サマリー

レシピデータを分離した

### 実際のコード

``` ruby
class RecipeData
  DATA = [
    'オムライス'
  ].map(&:freeze).freeze
end
```

### どうしてリーダブルだと考えたかの説明

レシピデータ用のクラスを分けた方が今後レシピデータに様々なプロパティが出てきても対応できると思った。

### 見つけた経緯

（「見つけた」場合のみ。ここに見つけた経緯を書く。）

**Comment by tkm-kj** [comment]
### サマリー

レシピデータにあるオムライスを出力できるようにした

### 実際のコード

``` ruby
require './recipe_data'

class Recipe
  def initialize(name)
    print_data(name)
  end

  private

  def print_data(name)
    puts RecipeData::DATA.find {|d| name == d }
  end
end

Recipe.new('オムライス')
```

### どうしてリーダブルだと考えたかの説明

レシピデータを出力する処理を別に分けた方が読む際にわかりやすいと思った。

### 見つけた経緯

（「見つけた」場合のみ。ここに見つけた経緯を書く。）

**Comment by tkm-kj** [comment]
### サマリー

レシピデータを3つにした

### 実際のコード

``` ruby
class RecipeData
  DATA = [
    'オムライス',
    '親子丼',
    '杏仁豆腐'
  ].map(&:freeze).freeze
end
```

### どうしてリーダブルだと考えたかの説明

### 見つけた経緯

（「見つけた」場合のみ。ここに見つけた経緯を書く。）

**Comment by tkm-kj** [comment]
### サマリー

レシピデータを全て出力できるようにした

### 実際のコード

``` ruby
require './recipe_data'

class Recipe
  def initialize
    print_data
  end

  private

  def print_data
    RecipeData::DATA.each do |name|
      puts name
    end
  end
end

Recipe.new
```

### どうしてリーダブルだと考えたかの説明

メソッドの引数が不要になったため、引数を取らないように明示した。

### 見つけた経緯

（「見つけた」場合のみ。ここに見つけた経緯を書く。）

**Comment by tkm-kj** [comment]
### サマリー

個々のレシピにIDを振り出した

### 実際のコード

``` ruby
class RecipeData
  DATA = [
    {
      id:   1,
      name: 'オムライス'
    },
    {
      id:   2,
      name: '親子丼'
    },
    {
      id:   3,
      name: '杏仁豆腐'
    }
  ].freeze
end
```

### どうしてリーダブルだと考えたかの説明

idとnameの値の縦がずれてるのが気になったので、同じインデントの深さにした。

### 見つけた経緯

（「見つけた」場合のみ。ここに見つけた経緯を書く。）

**Comment by tkm-kj** [comment]
### サマリー

IDとレシピ名を出力するようにした

### 実際のコード

``` ruby
require './recipe_data'

class Recipe
  def initialize
    print_data
  end

  private

  def print_data
    RecipeData::DATA.each do |recipe|
      puts "#{recipe[:id]}: #{recipe[:name]}"
    end
  end
end

Recipe.new
```

### どうしてリーダブルだと考えたかの説明

nameだけじゃなくidも出力するため、each内の変数名をnameからrecipeにした。

### 見つけた経緯

（「見つけた」場合のみ。ここに見つけた経緯を書く。）

**Comment by redcap97** [comment]
### サマリー

レシピ名をクラスにする

### 実際のコード

``` ruby
module RecipeManagement
  class Recipe
    attr_reader :name

    def initialize(name:)
      @name = name
    end
  end
end
```

### どうしてリーダブルだと考えたかの説明

クラスにすることで読みやすくなる。
拡張もしやすい。

### 見つけた経緯

（「見つけた」場合のみ。ここに見つけた経緯を書く。）

**Comment by rinkei** [comment]
### サマリー

出力フォーマットを統一する

### 実際のコード

``` ruby
def output(id, name)
  puts "#{id}: #{name}"
end
```

### どうしてリーダブルだと考えたかの説明

分岐ごとに出力を記述していたのでまとめた

### 見つけた経緯

ひとまず全ての仕様を書いてみて、共通している箇所だったので

**Comment by alpaca-tc** [comment]
### サマリー

`Recipe#to_s`を使って出力を行う

### 実際のコード

``` ruby
class Recipe
  @@next_id = 1
  attr_accessor :id, :title

  def initialize(title)
    @title = title
    @id = @@next_id

    @@next_id += 1
  end

  def to_s
    "#{id}: #{title}"
  end
end

recipes.each do |recipe|
  puts recipe
end
```

### どうしてリーダブルだと考えたかの説明

通常は`puts "#{recipe.id} #{recipe.title}"と書くけれど、to_sを利用することでクラスを出力するだけで済むのでシンプル

**Comment by moyashipan** [comment]
### サマリー

READMEにインストールの手順から書かれている

### 実際のコード

```
git clone https://alpaca-tc/alpaca-tc-rcw
```

### どうしてリーダブルだと考えたかの説明

公開されているgemなどでもGemfileにどうかけば良いかが書いてあると手順を進めやすい。
暗黙的じゃなく明示的なほうがつまづく可能性が低い。

### 見つけた経緯

**Comment by alpaca-tc** [comment]
### サマリー

明瞭な変数名 (`@@next_id`)

### 実際のコード

``` ruby
class Recipe
  @@next_id = 1
  attr_accessor :id, :title

  def initialize(title)
    @title = title
    @id = @@next_id

    @@next_id += 1
  end

  def to_s
    "#{id}: #{title}"
  end
end
```

### どうしてリーダブルだと考えたかの説明

`次のID`を意味することが明瞭で良い。

**Comment by alpaca-tc** [comment]
### サマリー

エラー内容と、次に行うべき動作がコードに記述されている

### 実際のコード

``` ruby
def parse_recipe_path!
  unless ARGV.length == 1
    puts <<-'EOS'
Invalid args.
Run like this: `ruby recipe.rb recipe.yaml`
    EOS
    exit
  end

  ARGV[0]
end
```

### どうしてリーダブルだと考えたかの説明

コードを実行した際にエラーが起きても、エラーの原因と正しい実行方法がエラーとして出力されるのでつまづかない。

**Comment by ik11235** [comment]
### サマリー

出力処理のメソッド化

### 実際のコード

``` ruby
def output(id, name)
  puts "#{id}: #{name}"
end
```

### どうしてリーダブルだと考えたかの説明

メソッド名から行う処理が明確かつ、出力のフォーマットが決まったうえここで定義されているということが、すぐに分かったため。

### 見つけた経緯

コードを見ていく過程でほぼ先頭で定義されておりすぐに目に入り、
また上記の理由から処理の内容が明確にわかったため

**Comment by rinkei** [comment]
### サマリー

IDの初期値を設定する

### 実際のコード

``` ruby
RECIPE_ID_START_VALUE = 1
```

### どうしてリーダブルだと考えたかの説明

コンテナの添字とIDを切り分けることができて良い。

### 見つけた経緯

自分は添字に+1した値をIDとしていたが、添字の初期値とIDの末番が一致しない時には使えないので

**Comment by moyashipan** [comment]
### サマリー

ヘルプオプションが用意されている

### 実際のコード

``` ruby
def parse!
  opts = OptionParser.new

  opts.on('-i', '--id [Recipe ID]', Integer) do |
    configuration[:recipe_id] = id
  end

  opts.on('--path [Recipe YAML DATA]') do |path|
    configuration[:recipe_path] = path
  end

  opts.parse!(@argv)
end
```

### どうしてリーダブルだと考えたかの説明

実行時にいちいちREADMEを見る必要がない。
多くのコマンドのデフォルトの挙動に則している。

### 見つけた経緯

READMEを読んで

**Comment by hayasaito** [comment]
### サマリー

レシピをクラスに読み込む

### 実際のコード

``` ruby
    def initialize(recipe_data_path:)
      @recipes = load_recipes(recipe_data_path)
    end
```

### どうしてリーダブルだと考えたかの説明

load_resipesの内容を見なくても
ファイル名を受け取って、
@resipesに"複数"のレシピを格納するとわかる

### 見つけた経緯

**Comment by furoshiki** [comment]
## サマリー

定数データに対して、操作メソッドをセットで提供。

## 実際のコード

```
class RecipeData
  DATA = [
    {
      id:   1,
      name: 'オムライス'
    },
    {
      id:   2,
      name: '親子丼'
    },
    {
      id:   3,
      name: '杏仁豆腐'
    }
  ].freeze

  class << self
    def find_recipe_data(id)
      DATA.find {|recipe| recipe[:id] == id }
    end
  end
end
```

## どうしてリーダブルだと考えたかの説明

呼び出し元のソースコードが定数だらけで汚れるのを防げている。

## 見つけた経緯

recipe_dataの拡張子が、txtでなくrbになっていた。

**Comment by tkm-kj** [comment]
### サマリー

変数名、メソッド名、クラス名が何を示しているかがわかりやすい。

### 実際のコード

``` ruby
class RecipeAccessor
  # レシピ情報を読み込む
  #  file_path : 情報が置かれているファイルがあれば、指定可能
  def initialize(file_path=nil)
    @current_id = 1
    @recipeList = []
    # ファイルがある場合は、そこから情報を取得する
    exit unless file_path
    begin
      File.open file_path do |recipe_data|
        recipe_data.each_line do |recipe_name|
          recipe_name = recipe_name.chomp
          add_recipe(recipe_name)
        end
      end
    rescue
      # ファイルが読み込めない場合は、何もしない
    end
  end
  # レシピを追加する
  def add_recipe(name)
    recipe = Recipe.new(@current_id,name)
    @recipeList.push(recipe)
    @current_id += 1
  end
  # 全レシピ情報のイテレーター
  def each_all
    @recipeList.each do |recipe|
      yield recipe
    end
  end
end
```

### どうしてリーダブルだと考えたかの説明

レシピの情報にアクセスするクラス（RecipeAccessor）やレシピのリスト(@recipeList)等、名前が何を意図しているかが伝わる。

### 見つけた経緯

コードを上から読んでいって。

**Comment by redcap97** [comment]
### サマリー

コレクション用のクラスを定義している

### 実際のコード

``` ruby
class Resipe
  def initialize(name)
    @name = name
  end
end

class Resipes

    def initialize
        @resipes = []
    end

    def add (resipe)
      @resipes << resipe
    end

    def putAll
        @resipes.each do |resipe|
            puts(resipe.name)
    end
end
```

### どうしてリーダブルだと考えたかの説明

配列をクラスにしているのでデータ列への操作を綺麗に保てそう。

**Comment by hayasaito** [comment]
### サマリー

ファイルから行を読み込んで個々のレシピ用の変数に格納する

### 実際のコード

``` ruby
    def load_recipes(recipe_data_path)
      lines = File.readlines(recipe_data_path)
      lines.map { |line| Recipe.new(name: line) }
    end
```

### どうしてリーダブルだと考えたかの説明

.mapは知らなかったが
仮変数lineに1行ずつ取り出し、それをResipieのnameプロパティに記録して
Resipeのインスタンスを返すことが明確にわかる。

### 見つけた経緯

**Comment by ik11235** [comment]
### サマリー

データ名称、形式の明確化

### 実際のコード

``` yaml
- name: オムライス
- name: 親子丼
- name: 杏仁豆腐
```

### どうしてリーダブルだと考えたかの説明

レシピデータの中身が、レシピの何を表しているか明確にわかり、また新しい情報を追加しやすい形になっているため

### 見つけた経緯

データを更新するために開いた際に、データの中身がすぐにわかったため

**Comment by hayasaito** [comment]
### サマリー

レシピを格納するクラスをrequireして
全体の見通しを良くしている。

### 実際のコード

``` ruby
require 'recipe_management/recipe'

module RecipeManagement
  class Application
  ...
```

### どうしてリーダブルだと考えたかの説明

レシピを格納するクラスをrequireして
全体の見通しを良くしている。

### 見つけた経緯

自分のコードでレシピ管理クラスを処理より下に記述したら
未初期化定数とみなされて動作しなかった。
