### ISSUE TITLE
GroupB のまとめ用

### ISSUE THREAD

**Issue by toshi0383** [clear-code/readable-code-workshop#6]
ここに、memo.mdへのURLを貼ってくださいまし。

**Comment by sn1w** [comment]
# 変数名の工夫
- コードへのリンク
  https://github.com/shiwai/isozumi-readable-code/commit/d24fca4abd2e117e38c7b2d83d333eed079ff704
- リーダブルな理由
  変数名が目的に沿った適切なもののため、読むときに困ることがなかった

**Comment by terahide** [comment]
## ガード条件

コード 

if (!file.exists()) {
    return recipes;
}

メソッドの中やループの中の早いタイミングでリターン（continue or break）する

## Javadocコメントが付いている

https://github.com/terahide/toshi0383-readable-code/blob/master/src/Recipe.java#L70
仕様が見えやすい

## インデントが揃っている

全体的に
見やすい

## 一時変数で名前をつけている

https://github.com/terahide/toshi0383-readable-code/blob/master/src/Recipe.java#L26

String fileName = args[0]; 
コード args[0]だと意味が分からないだけどfileNameならわかる

##USAGEを定数にしている
https://github.com/terahide/toshi0383-readable-code/blob/master/src/Recipe.java#L15
コンテキスト外の情報を定数にして外に追い出している（コンテクストに集中できる）

## クラスの名前がRecipe

https://github.com/terahide/toshi0383-readable-code/blob/master/src/Recipe.java#L12
役割に対して適切な名前を付けている

## 変数の名前を１文字にせずに名前を付けている

https://github.com/terahide/toshi0383-readable-code/blob/master/src/Recipe.java#L72
役割に対して適切な名前を付けている

## 不要なコメントがない

全体
ノイズが少ない。コードで意図を伝えられている証拠

## インデントが浅い最大３階層

全体
https://github.com/terahide/toshi0383-readable-code/blob/master/src/Recipe.java#L53

読みやすい

## ジェネリクスを使って型をしばる （Java特有）e.g. List<String>

https://github.com/terahide/toshi0383-readable-code/blob/master/src/Recipe.java#L71
Collectionの要素も型安全で意図を伝えやすい

**Comment by toshi0383** [comment]
## 変数やクラス名がすべて日本語で読みやすい

https://github.com/terahide/terahide-readable-code/blob/master/src/main/java/readablecode/sample/%E3%83%AC%E3%82%B7%E3%83%94.java#L10

```
public class レシピ {
  public void コンソールに表示する(){
    List<String> 料理名たち = 料理名を読み込む();
    for (String 料理名 : 料理名たち) {
      コンソールに表示する(料理名);
    }
  }
```

頭の中で翻訳しなくてもよいから

## ファイルの読み込みクラスを設ける

https://github.com/terahide/terahide-readable-code/blob/master/src/main/java/readablecode/sample/%E3%83%AC%E3%82%B7%E3%83%94.java#L29

```
  private static class システム都合のヘルパ{
    private static List<String> read料理File(){
      return readFile("料理.txt");
    }
    private static List<String> readFile(String f){
      return read(new File(f));
    }
    @SuppressWarnings("unchecked")
    private static List<String> read(File f){
      try {
        return FileUtils.readLines(f);
      } catch (IOException e) {
        throw new RuntimeException(e);
      }
    }
    private static String createId() {
      return UUID.randomUUID().toString();
    }
  }
```

使いやすいし、読みやすい。

## パッケージを分ける

https://github.com/terahide/terahide-readable-code/blob/master/src/main/java/readablecode/sample/%E3%83%AC%E3%82%B7%E3%83%94.java#L1
パッケージが分けてあって、あとから機能追加する際に整理しやすい

**Comment by isozumi** [comment]
# 備忘
-  ファイルの読み込み処理はドメインに依存しないので別クラスに切り出す

# リーダブルなところ
-  目的に応じたクラスの細分化
  コード：RecipeManagementConsole、RecipeManager、RecipeUtilitiesなどのクラス
  https://github.com/isozumi/shiwai-readable-code/blob/master/src/com/weekinweekout/RecipeManegementConsole.java#L10
  https://github.com/isozumi/shiwai-readable-code/blob/master/src/com/weekinweekout/util/Utilities.java#L9
  リーダブルな理由：コードを読む際に、目的がわかりやすい。mainの記載がすっきりして処理の概要がつかみやすい。
  見つけたきっかけ：「ファイル読み込みのロジックはどうなっているんだろう？」と疑問に思ったときに、ファイルを開く選択だけでたどり着けた
-  目的と対象の変数名への反映
  コード：outputRecipesToConsole,readLinesFromFileなどの変数
  https://github.com/isozumi/shiwai-readable-code/blob/master/src/com/weekinweekout/RecipeManegementConsole.java#L22
  リーダブルな理由：コードを読む際に、目的がわかりやすい。mainの記載がすっきりして処理の概要がつかみやすい。
  見つけたきっかけ：「ファイル読み込みのロジックはどうなっているんだろう？」と疑問に思ったときに、ファイルを開く選択だけでたどり着けた
-  リスト型の変数は複数形の命名

**Comment by kou** [comment]
まとめが終わったので閉じておきます。
